export const WORLD_CUP_TEAMS = [
  'Algeria',
  'Arabia Saudita',
  'Argentina',
  'Australia',
  'Austria',
  'Belgio',
  'Bosnia ed Erzegovina',
  'Brasile',
  'Canada',
  'Capo Verde',
  'Repubblica Ceca',
  'Colombia',
  'Corea del Sud',
  'Costa d\'Avorio',
  'Croazia',
  'Curaçao',
  'Ecuador',
  'Egitto',
  'Francia',
  'Germania',
  'Ghana',
  'Giappone',
  'Giordania',
  'Haiti',
  'Inghilterra',
  'Iran',
  'Iraq',
  'Marocco',
  'Messico',
  'Norvegia',
  'Nuova Zelanda',
  'Paesi Bassi',
  'Panama',
  'Paraguay',
  'Portogallo',
  'Qatar',
  'RD del Congo',
  'Scozia',
  'Senegal',
  'Spagna',
  'Stati Uniti',
  'Sudafrica',
  'Svezia',
  'Svizzera',
  'Tunisia',
  'Turchia',
  'Uruguay',
  'Uzbekistan'
] as const;

export type WorldCupTeam = typeof WORLD_CUP_TEAMS[number];
